import type { MenuCategory, MenuProduct } from "@/types/menu.types";

export const menuCategories: MenuCategory[] = [
  { id: 1, slug: "ca-phe", name: "Cà Phê", icon: "☕", description: "Đặc sản cà phê Việt Nam" },
  { id: 2, slug: "tra", name: "Trà", icon: "🍵", description: "Trà xanh, trà hoa tinh tế" },
  { id: 3, slug: "freeze", name: "Freeze", icon: "🧊", description: "Đồ uống đá xay mát lạnh" },
  { id: 4, slug: "phindi", name: "Phindi", icon: "🥛", description: "Cà phê phin đá đặc trưng" },
  { id: 5, slug: "banh-mi-que", name: "Bánh Mì Que", icon: "🥖", description: "Bánh mì que giòn rụm" },
  { id: 6, slug: "banh-ngot", name: "Bánh Ngọt", icon: "🍰", description: "Bánh ngọt Pháp - Nhật cao cấp" },
  { id: 7, slug: "tra-sua", name: "Trà Sữa Hylux", icon: "🧋", description: "Trà sữa signature Hylux" },
];

export const menuProducts: MenuProduct[] = [
  // Cà Phê (categoryId: 1)
  {
    id: 1, sku: "CF001", categoryId: 1,
    name: "Cà Phê Sữa Đá",
    description: "Phin truyền thống, sữa đặc Ông Thọ",
    content: "Cà phê được pha từ hạt Robusta Buôn Ma Thuột, kết hợp với sữa đặc Ông Thọ tạo nên hương vị đậm đà, ngọt ngào đặc trưng Việt Nam.",
    price: 29000, originalPrice: 35000,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600",
    images: ["https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800", "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800"],
    rating: 4.8, reviewCount: 234, isAvailable: true, isFeatured: true, tags: ["bestseller", "classic"],
  },
  {
    id: 2, sku: "CF002", categoryId: 1,
    name: "Bạc Xỉu",
    description: "Vị nhẹ nhàng, tỷ lệ sữa đặc cao",
    content: "Bạc Xỉu - thức uống hoàn hảo cho những ai yêu thích vị cà phê nhẹ nhàng, ngọt ngào.",
    price: 32000,
    image: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=600",
    rating: 4.6, reviewCount: 189, isAvailable: true, isFeatured: true,
  },
  {
    id: 3, sku: "CF003", categoryId: 1,
    name: "Americano",
    description: "Espresso pha loãng với nước nóng",
    content: "Americano được pha từ 2 shot espresso với nước nóng, mang đến hương vị cà phê thuần khiết.",
    price: 39000,
    image: "https://images.unsplash.com/photo-1551030173-122aabc4489c?w=600",
    rating: 4.5, reviewCount: 156, isAvailable: true,
  },
  {
    id: 4, sku: "CF004", categoryId: 1,
    name: "Cappuccino",
    description: "Espresso, sữa nóng và foam mịn chuẩn Ý",
    content: "Cappuccino chuẩn Ý với tỷ lệ 1/3 espresso, 1/3 sữa nóng và 1/3 foam mịn như nhung.",
    price: 45000,
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600",
    rating: 4.7, reviewCount: 312, isAvailable: true, isFeatured: true,
  },
  {
    id: 5, sku: "CF005", categoryId: 1,
    name: "Caramel Latte",
    description: "Espresso, sữa tươi và caramel ngọt",
    content: "Caramel Latte với espresso đậm hòa quyện sữa tươi béo và caramel thơm ngọt.",
    price: 52000,
    image: "https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=600",
    rating: 4.8, reviewCount: 278, isAvailable: true,
  },
  {
    id: 6, sku: "CF006", categoryId: 1,
    name: "Cold Brew",
    description: "Ủ lạnh 24h, vị đậm mượt mà",
    content: "Cold Brew ủ lạnh 24 giờ với tỷ lệ cà phê 1:4, mang đến vị đậm đà, ít đắng, mượt mà.",
    price: 49000,
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600",
    rating: 4.9, reviewCount: 198, isAvailable: true, isFeatured: true, tags: ["new"],
  },

  // Trà (categoryId: 2)
  {
    id: 7, sku: "TE001", categoryId: 2,
    name: "Trà Sen Vàng",
    description: "Trà ướp hương sen Tây Hồ thanh nhã",
    content: "Trà sen vàng được ướp từ hoa sen Tây Hồ, hương thơm thanh nhã, vị trà ngọt hậu.",
    price: 35000,
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600",
    rating: 4.6, reviewCount: 145, isAvailable: true, isFeatured: true,
  },
  {
    id: 8, sku: "TE002", categoryId: 2,
    name: "Trà Đào Cam Sả",
    description: "Đào ngọt, cam tươi, sả thơm",
    content: "Sự kết hợp hoàn hảo giữa trà đào ngọt ngào, cam tươi thanh mát và sả thơm dịu.",
    price: 45000, originalPrice: 55000,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600",
    rating: 4.9, reviewCount: 423, isAvailable: true, isFeatured: true, tags: ["bestseller"],
  },
  {
    id: 9, sku: "TE003", categoryId: 2,
    name: "Trà Ô Long Sữa",
    description: "Trà ô long rang vừa, sữa tươi béo",
    content: "Trà ô long rang vừa, hương thơm đặc trưng kết hợp với sữa tươi béo ngậy.",
    price: 42000,
    image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600",
    rating: 4.5, reviewCount: 198, isAvailable: true,
  },
  {
    id: 10, sku: "TE004", categoryId: 2,
    name: "Trà Xanh Matcha",
    description: "Matcha Nhật rang đậm vị umami",
    content: "Matcha cấp độ ceremonial từ Uji Nhật Bản, vị đậm đà umami, màu xanh đẹp.",
    price: 55000,
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600",
    rating: 4.7, reviewCount: 267, isAvailable: true, isFeatured: true,
  },

  // Freeze (categoryId: 3)
  {
    id: 11, sku: "FZ001", categoryId: 3,
    name: "Caramel Freeze",
    description: "Đá xay, caramel và whipped cream",
    content: "Caramel Freeze với đá xay mịn, sốt caramel thơm và lớp kem whipped bồng bềnh.",
    price: 55000,
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600",
    rating: 4.8, reviewCount: 312, isAvailable: true, isFeatured: true,
  },
  {
    id: 12, sku: "FZ002", categoryId: 3,
    name: "Chocolate Freeze",
    description: "Đá xay chocolate đậm vị",
    content: "Chocolate Freeze với bột cacao Bỉ, đá xay và kem tươi topped.",
    price: 58000,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600",
    rating: 4.7, reviewCount: 245, isAvailable: true,
  },
  {
    id: 13, sku: "FZ003", categoryId: 3,
    name: "Matcha Freeze",
    description: "Matcha Nhật đá xay mát lạnh",
    content: "Matcha Uji nguyên chất, đá xay mịn, sữa tươi và lớp kem phô mai mặn ngọt.",
    price: 62000,
    image: "https://images.unsplash.com/photo-1628711426032-c03a0dd8c671?w=600",
    rating: 4.9, reviewCount: 189, isAvailable: true, tags: ["new"],
  },
  {
    id: 14, sku: "FZ004", categoryId: 3,
    name: "Strawberry Freeze",
    description: "Dâu Đà Lạt tươi, đá xay ngọt mát",
    content: "Dâu tây Đà Lạt tươi xay cùng đá và sữa chua, vị chua ngọt hài hòa.",
    price: 59000,
    image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=600",
    rating: 4.6, reviewCount: 176, isAvailable: true,
  },

  // Phindi (categoryId: 4)
  {
    id: 15, sku: "PD001", categoryId: 4,
    name: "Phindi Nguyên Bản",
    description: "Cà phê phin đá đặc trưng Hylux",
    content: "Phindi signature của Hylux: cà phê Robusta phin chậm, pha với đá viên to và sữa đặc.",
    price: 35000,
    image: "https://images.unsplash.com/photo-1459755486867-b55449bb39ff?w=600",
    rating: 4.8, reviewCount: 356, isAvailable: true, isFeatured: true, tags: ["signature"],
  },
  {
    id: 16, sku: "PD002", categoryId: 4,
    name: "Phindi Dừa",
    description: "Phin đá kết hợp nước dừa tươi mát",
    content: "Sự kết hợp độc đáo giữa cà phê phin đậm và nước dừa tươi ngọt mát.",
    price: 42000,
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600",
    rating: 4.7, reviewCount: 234, isAvailable: true,
  },
  {
    id: 17, sku: "PD003", categoryId: 4,
    name: "Phindi Muối Caramel",
    description: "Phin đá, caramel muối biển đặc biệt",
    content: "Phindi với topping caramel muối biển, cân bằng giữa vị ngọt caramel và mặn tinh tế.",
    price: 48000,
    image: "https://images.unsplash.com/photo-1562547256-2c5ee93b60b8?w=600",
    rating: 4.9, reviewCount: 289, isAvailable: true, isFeatured: true, tags: ["bestseller"],
  },

  // Bánh Mì Que (categoryId: 5)
  {
    id: 18, sku: "BM001", categoryId: 5,
    name: "Bánh Mì Que Phô Mai",
    description: "Giòn rụm, nhân phô mai tan chảy",
    content: "Bánh mì que nướng giòn với nhân phô mai Edam tan chảy và hành lá thơm.",
    price: 18000,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600",
    rating: 4.7, reviewCount: 456, isAvailable: true, isFeatured: true,
  },
  {
    id: 19, sku: "BM002", categoryId: 5,
    name: "Bánh Mì Que Thịt Nguội",
    description: "Jambon, pate và rau thơm",
    content: "Bánh mì que kiểu Pháp với jambon, pate gan, dưa leo, cà chua và tương ớt.",
    price: 22000,
    image: "https://images.unsplash.com/photo-1565299543923-37dd37887442?w=600",
    rating: 4.6, reviewCount: 312, isAvailable: true,
  },
  {
    id: 20, sku: "BM003", categoryId: 5,
    name: "Bánh Mì Que Trứng",
    description: "Trứng chiên, xúc xích và rau tươi",
    content: "Bữa sáng hoàn hảo với bánh mì que nhân trứng ốp la, xúc xích và rau tươi.",
    price: 20000,
    image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=600",
    rating: 4.5, reviewCount: 278, isAvailable: true,
  },
  {
    id: 21, sku: "BM004", categoryId: 5,
    name: "Bánh Mì Que Kẹp Kem",
    description: "Bánh que giòn kẹp kem và dâu",
    content: "Bánh mì que nướng giòn kẹp kem vani và dâu tươi, kết hợp ngọt mặn lạ miệng.",
    price: 25000,
    image: "https://images.unsplash.com/photo-1514516816566-de580c8f8396?w=600",
    rating: 4.8, reviewCount: 189, isAvailable: true, tags: ["new"],
  },

  // Bánh Ngọt (categoryId: 6)
  {
    id: 22, sku: "PA001", categoryId: 6,
    name: "Bánh Croissant",
    description: "27 lớp bơ Anchor nướng vàng giòn",
    content: "Croissant nướng giòn với 27 lớp bơ Anchor, thơm lừng và tan trong miệng.",
    price: 35000,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600",
    rating: 4.9, reviewCount: 345, isAvailable: true, isFeatured: true,
  },
  {
    id: 23, sku: "PA002", categoryId: 6,
    name: "Bánh Tiramisu",
    description: "Mascarpone Ý, espresso, rượu Marsala",
    content: "Tiramisu làm từ mascarpone Ý, cà phê espresso và rượu Marsala, hương vị đậm đà.",
    price: 55000,
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600",
    rating: 4.8, reviewCount: 287, isAvailable: true,
  },
  {
    id: 24, sku: "PA003", categoryId: 6,
    name: "Cheesecake Nhật",
    description: "Mềm mịn tan ngay kiểu fluffy Nhật",
    content: "Japanese cheesecake mềm như bông, tan ngay khi chạm lưỡi với vị phô mai thanh nhẹ.",
    price: 52000,
    image: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=600",
    rating: 4.7, reviewCount: 198, isAvailable: true,
  },
  {
    id: 25, sku: "PA004", categoryId: 6,
    name: "Eclair Cà Phê",
    description: "Eclair Pháp nhân kem cà phê",
    content: "Eclair nướng vàng, nhân kem custard cà phê đậm và lớp glaze chocolate bóng.",
    price: 45000,
    image: "https://images.unsplash.com/photo-1558326567-98166e232c52?w=600",
    rating: 4.6, reviewCount: 156, isAvailable: true, tags: ["new"],
  },

  // Trà Sữa Hylux (categoryId: 7)
  {
    id: 26, sku: "TS001", categoryId: 7,
    name: "Trà Sữa Trân Châu Đen",
    description: "Classic bubble tea trân châu đen Q dai",
    content: "Trà sữa signature với trân châu đen tự nấu, Q dai và hương vị hòa quyện ngọt ngào.",
    price: 45000,
    image: "https://images.unsplash.com/photo-1558857563-b371033873b8?w=600",
    rating: 4.9, reviewCount: 678, isAvailable: true, isFeatured: true, tags: ["bestseller"],
  },
  {
    id: 27, sku: "TS002", categoryId: 7,
    name: "Trà Sữa Matcha Đỏ",
    description: "Matcha Nhật phủ trân châu đỏ",
    content: "Trà sữa matcha với trân châu đỏ nấu đường phèn, vị đậm umami và ngọt thanh.",
    price: 52000,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600",
    rating: 4.8, reviewCount: 423, isAvailable: true, isFeatured: true,
  },
  {
    id: 28, sku: "TS003", categoryId: 7,
    name: "Trà Sữa Hoa Hồng",
    description: "Trà hoa hồng, sữa tươi và foam cheese",
    content: "Trà hoa hồng thơm ngát, sữa tươi béo và lớp cheese foam mặn ngọt đặc trưng.",
    price: 55000,
    image: "https://images.unsplash.com/photo-1574594891041-18e57f3484e9?w=600",
    rating: 4.7, reviewCount: 234, isAvailable: true,
  },
  {
    id: 29, sku: "TS004", categoryId: 7,
    name: "Trà Sữa Taro",
    description: "Khoai môn Đà Lạt, màu tím tự nhiên",
    content: "Trà sữa taro làm từ khoai môn Đà Lạt xay nhuyễn, màu tím tự nhiên bắt mắt.",
    price: 48000,
    image: "https://images.unsplash.com/photo-1593620659530-8673c77513d9?w=600",
    rating: 4.8, reviewCount: 345, isAvailable: true, isFeatured: true,
  },
  {
    id: 30, sku: "TS005", categoryId: 7,
    name: "Trà Sữa Black Tiger",
    description: "Trà đen, tiger syrup và trân châu hổ",
    content: "Black Tiger trà sữa với tiger syrup ombre đẹp mắt và trân châu hổ đặc trưng.",
    price: 58000,
    image: "https://images.unsplash.com/photo-1527156231393-7023794f363c?w=600",
    rating: 4.9, reviewCount: 512, isAvailable: true, tags: ["trending"],
  },

  // Thêm sản phẩm test
  {
    id: 31, sku: "CF007", categoryId: 1,
    name: "Espresso Đá",
    description: "Espresso đậm rót thẳng lên đá",
    content: "Espresso double shot rót thẳng lên đá viên to, uống ngay để cảm nhận độ đậm đà.",
    price: 35000,
    image: "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=600",
    rating: 4.6, reviewCount: 120, isAvailable: true,
  },
  {
    id: 32, sku: "CF008", categoryId: 1,
    name: "Flat White",
    description: "Ristretto, microfoam sữa mịn",
    content: "Flat White với ristretto đậm và microfoam sữa cực mịn, latte art tinh tế.",
    price: 48000,
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600",
    rating: 4.7, reviewCount: 98, isAvailable: true,
  },
  {
    id: 33, sku: "CF009", categoryId: 1,
    name: "Mocha",
    description: "Espresso, chocolate, sữa tươi",
    content: "Mocha kết hợp espresso đậm, chocolate Valrhona và sữa tươi béo ngậy.",
    price: 52000,
    image: "https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=600",
    rating: 4.8, reviewCount: 210, isAvailable: true,
  },
  {
    id: 34, sku: "CF010", categoryId: 1,
    name: "Vanilla Latte",
    description: "Espresso, sữa và vanilla syrup",
    content: "Vanilla Latte ngọt dịu với espresso, sữa tươi và vanilla syrup Madagascar.",
    price: 50000,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600",
    rating: 4.6, reviewCount: 165, isAvailable: true,
  },
  {
    id: 35, sku: "TE005", categoryId: 2,
    name: "Trà Lài Mật Ong",
    description: "Trà hoa lài, mật ong nguyên chất",
    content: "Trà lài thơm ngát pha với mật ong rừng nguyên chất, thanh mát và nhẹ nhàng.",
    price: 38000,
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=600",
    rating: 4.5, reviewCount: 88, isAvailable: true,
  },
  {
    id: 36, sku: "TE006", categoryId: 2,
    name: "Trà Bạc Hà Chanh",
    description: "Bạc hà tươi, chanh leo, trà xanh",
    content: "Trà bạc hà thơm mát kết hợp chanh leo và trà xanh Thái Nguyên tươi ngon.",
    price: 40000,
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600",
    rating: 4.7, reviewCount: 134, isAvailable: true,
  },
  {
    id: 37, sku: "FZ005", categoryId: 3,
    name: "Taro Freeze",
    description: "Khoai môn Đà Lạt xay đá mịn",
    content: "Taro Freeze với khoai môn Đà Lạt tươi xay cùng đá, sữa và trân châu.",
    price: 60000,
    image: "https://images.unsplash.com/photo-1593620659530-8673c77513d9?w=600",
    rating: 4.8, reviewCount: 201, isAvailable: true,
  },
  {
    id: 38, sku: "FZ006", categoryId: 3,
    name: "Oreo Freeze",
    description: "Oreo nghiền, kem tươi, cacao",
    content: "Oreo Freeze với bánh Oreo nghiền mịn, đá xay, kem tươi và sốt chocolate.",
    price: 62000,
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=600",
    rating: 4.7, reviewCount: 178, isAvailable: true,
  },
  {
    id: 39, sku: "PD004", categoryId: 4,
    name: "Phindi Cam",
    description: "Phin đá kết hợp nước cam tươi vắt",
    content: "Phindi cam độc đáo với cà phê phin đậm và nước cam tươi vắt chua ngọt hài hòa.",
    price: 45000,
    image: "https://images.unsplash.com/photo-1459755486867-b55449bb39ff?w=600",
    rating: 4.6, reviewCount: 112, isAvailable: true,
  },
  {
    id: 40, sku: "PD005", categoryId: 4,
    name: "Phindi Dâu",
    description: "Phin đá, sốt dâu Đà Lạt tươi",
    content: "Phindi dâu với cà phê phin đậm và sốt dâu Đà Lạt tươi ngọt, màu sắc bắt mắt.",
    price: 48000,
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600",
    rating: 4.8, reviewCount: 145, isAvailable: true, tags: ["new"],
  },
  {
    id: 41, sku: "TS006", categoryId: 7,
    name: "Trà Sữa Dưa Hấu",
    description: "Dưa hấu Quảng Nam, sữa tươi mát",
    content: "Trà sữa dưa hấu với nước dưa hấu Quảng Nam tươi ép, sữa tươi và thạch dừa.",
    price: 50000,
    image: "https://images.unsplash.com/photo-1558857563-b371033873b8?w=600",
    rating: 4.7, reviewCount: 189, isAvailable: true,
  },
  {
    id: 42, sku: "TS007", categoryId: 7,
    name: "Trà Sữa Khoai Lang Tím",
    description: "Khoai lang tím Nhật, sữa béo",
    content: "Trà sữa khoai lang tím Nhật với màu tím tự nhiên đẹp mắt, vị ngọt thanh béo ngậy.",
    price: 55000,
    image: "https://images.unsplash.com/photo-1574594891041-18e57f3484e9?w=600",
    rating: 4.8, reviewCount: 267, isAvailable: true,
  },
  {
    id: 43, sku: "PA005", categoryId: 6,
    name: "Bánh Madeleine",
    description: "Bánh bông lan bơ kiểu Pháp",
    content: "Madeleine nướng mềm với bơ Pháp và vỏ chanh, thơm ngậy và mềm xốp.",
    price: 28000,
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600",
    rating: 4.5, reviewCount: 98, isAvailable: true,
  },
  {
    id: 44, sku: "PA006", categoryId: 6,
    name: "Tart Chanh Dây",
    description: "Vỏ tart giòn, nhân chanh dây chua ngọt",
    content: "Tart chanh dây với vỏ sablé giòn tan, nhân lemon curd từ chanh dây Tây Nguyên.",
    price: 42000,
    image: "https://images.unsplash.com/photo-1524351199678-941a58a3df50?w=600",
    rating: 4.7, reviewCount: 134, isAvailable: true, tags: ["new"],
  },
  {
    id: 45, sku: "BM005", categoryId: 5,
    name: "Bánh Mì Que Nutella",
    description: "Bánh que giòn phết Nutella dày",
    content: "Bánh mì que nướng giòn phết đầy Nutella, rắc hạnh nhân và muối hồng Himalaya.",
    price: 27000,
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600",
    rating: 4.8, reviewCount: 223, isAvailable: true,
  },
  {
    id: 46, sku: "CF011", categoryId: 1,
    name: "Hazelnut Latte",
    description: "Espresso, sữa và hazelnut syrup",
    content: "Hazelnut Latte với espresso, sữa tươi béo và hazelnut syrup Torani thơm ngậy.",
    price: 52000,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=600",
    rating: 4.7, reviewCount: 143, isAvailable: true,
  },
  {
    id: 47, sku: "CF012", categoryId: 1,
    name: "Cà Phê Muối",
    description: "Cà phê đá, foam muối biển béo mặn",
    content: "Cà phê đá phủ lớp foam muối biển béo ngậy, mặn ngọt hài hòa đặc trưng miền Trung.",
    price: 45000,
    image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600",
    rating: 4.9, reviewCount: 312, isAvailable: true, tags: ["trending"],
  },
  {
    id: 48, sku: "TE007", categoryId: 2,
    name: "Trà Hibiscus Đá",
    description: "Hoa atiso đỏ, vị chua thanh mát",
    content: "Trà hibiscus pha lạnh với hoa atiso đỏ Ethiopia, vị chua nhẹ, đẹp mắt màu đỏ ruby.",
    price: 42000,
    image: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600",
    rating: 4.6, reviewCount: 76, isAvailable: true,
  },
  {
    id: 49, sku: "FZ007", categoryId: 3,
    name: "Mango Freeze",
    description: "Xoài Cát Hòa Lộc xay đá mịn",
    content: "Mango Freeze với xoài Cát Hòa Lộc chín xay cùng đá, sữa chua và thạch xoài.",
    price: 58000,
    image: "https://images.unsplash.com/photo-1570197788417-0e82375c9371?w=600",
    rating: 4.9, reviewCount: 234, isAvailable: true, tags: ["bestseller"],
  },
  {
    id: 50, sku: "TS008", categoryId: 7,
    name: "Trà Sữa Kem Cheese",
    description: "Trà đen, sữa tươi, foam cheese mặn",
    content: "Trà sữa thượng hạng với lớp cheese foam mặn ngọt đặc trưng phủ trên trà đen đậm.",
    price: 55000,
    image: "https://images.unsplash.com/photo-1527156231393-7023794f363c?w=600",
    rating: 4.9, reviewCount: 445, isAvailable: true, isFeatured: true, tags: ["bestseller"],
  },
];

export function getProductsByCategory(categoryId: number): MenuProduct[] {
  return menuProducts.filter((p) => p.categoryId === categoryId && p.isAvailable);
}

export function getProductById(id: number): MenuProduct | undefined {
  return menuProducts.find((p) => p.id === id);
}
